// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lurczbwtmavcfpqcckpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1cmN6Ynd0bWF2Y2ZwcWNja3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzU2NjYsImV4cCI6MjA2MzY1MTY2Nn0.0X5LamBi32k11E5ipcWL4Gkf9vhIm3Mq-DJC7bNnrlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);